apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-25T16:06:28.711267415+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: f562da7744a44b335afdb6e027c3ac9795fa2eb8d8338e4836c11ac5e435a68d
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.6.tgz
    version: 0.1.6
  nl-design-skeleton-gatsby:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-03-25T16:06:28.658264034+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/master/api/helm/
      version: 0.1.2
    description: Skeleton application for NL Design running on Gatsby
    digest: 3e948e40e389b8f79c8ec71025624d6bd82c59996afef2ed23b5c6172b960841
    name: nl-design-skeleton-gatsby
    type: application
    urls:
    - nl-design-skeleton-gatsby-0.1.0.tgz
    version: 0.1.0
  pwa-nijmegen:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-03-25T16:06:28.696575361+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.6
    description: Skeleton application for NL Design running on Gatsby
    digest: 23011185f598b170e72be77aae3ef638e7ae5703bc67838be0b22c6ff1bf5c75
    name: pwa-nijmegen
    type: application
    urls:
    - pwa-nijmegen-0.1.1.tgz
    version: 0.1.1
generated: "2022-03-25T16:06:28.631577303+01:00"
