apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-25T18:23:34.217748027+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: 0f72c855cd9276b06a6eb82f4f5e1367c9eff7629de3c2671c52de6db1300d74
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.7.tgz
    version: 0.1.7
  pwa-nijmegen:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-03-25T18:23:34.205255139+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/odyssey-hackathon-2022/api/helm/
      version: 0.1.7
    description: Skeleton application for NL Design running on Gatsby
    digest: 5254615c939dc8590b2d4f4a2b225ccf6409ecd19c6ceae379ddf43f0aa54392
    name: pwa-nijmegen
    type: application
    urls:
    - pwa-nijmegen-0.1.1.tgz
    version: 0.1.1
generated: "2022-03-25T18:23:34.191867032+01:00"
