apiVersion: v1
entries:
  commonground-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-03-25T16:10:33.354948379+01:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.5
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: f562da7744a44b335afdb6e027c3ac9795fa2eb8d8338e4836c11ac5e435a68d
    name: commonground-gateway
    type: application
    urls:
    - charts/commonground-gateway-0.1.6.tgz
    version: 0.1.6
  pwa-nijmegen:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-03-25T16:10:33.338416069+01:00"
    dependencies:
    - alias: gateway
      condition: gateway.enabled
      name: commonground-gateway
      repository: https://raw.githubusercontent.com/ConductionNL/commonground-gateway/feature-cleanup/api/helm/
      version: 0.1.6
    description: Skeleton application for NL Design running on Gatsby
    digest: 1788120c580c663cec6669e5475ceb6c3153df22e0f558ecff1cc6f156bad03e
    name: pwa-nijmegen
    type: application
    urls:
    - pwa-nijmegen-0.1.1.tgz
    version: 0.1.1
generated: "2022-03-25T16:10:33.322046398+01:00"
